apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-service-config
  namespace: default
data:
  application.yml: |
    step-ca:
      url: https://step.it.com
    proxy:
      trust-all-certs: true
    logging:
      level:
        com.example.proxyservice: INFO

---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: default
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
      - name: proxy-service
        image: proxy-service:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_CONFIG_LOCATION
          value: classpath:/application.yml,/app/config/application.yml
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: proxy-service-config
      - name: logs
        emptyDir: {}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-issuer
spec:
  acme:
    server: http://proxy-service:8080/acme/directory
    email: admin@example.com
    privateKeySecretRef:
      name: step-ca-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx

